### ISSUE TITLE
The capability to read input status,  coil, and input register

### ISSUE THREAD

**Issue by cloudxxx8** [IOTechSystems/device-modbus#9]
The current implementation only supports to read Modbus input registers.
Reading input status,  coil, and input register are all common requirement of usual Modbus devices.

**Comment by weichou1229** [comment]
- [ ] device-modbus should define enum PrimaryTable
- [ ] device-profile attributes define primaryTable address for modbus
- [ ] device-modbus should define enum properties value type: Integer , Float , Uint16 , Uint32 ,Uint64
- [ ] device-modbus when parse multi-register ,default first is hi-byte and second is low-byte ...
- [ ] device-profile address is direct map to PrimaryTable's address ,not starting address
- [ ] refactor test tool for connect device with modbus protocol
- [ ] refactor device-modbus

**Comment by cloudxxx8** [comment]
https://github.com/IOTechSystems/device-modbus/pull/14
